import type { Capability } from "../types.js";

export const CHINESE_CAPABILITIES: readonly Capability[] = [
  {
    provider: "dashscope",
    api: "chat.completions",
    modelPattern: "^qwen",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    baseURLIntl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    region: "cn",
    extraBody: { enable_thinking: false },
    streamTools: false,
    notes:
      "Qwen compatible-mode. Region-specific API keys. Some models reject tools with stream: true. Disable thinking before forcing a tool.",
  },
  {
    provider: "dashscope",
    api: "responses",
    modelPattern: "^qwen",
    tools: "yes",
    schemaDialect: "openai-strict",
    arguments: "string",
    parallel: true,
    strictDefault: true,
    auth: "bearer",
    baseURL: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    baseURLIntl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    region: "cn",
    extraBody: { enable_thinking: false },
    notes: "Qwen Cloud Responses-compatible function tools.",
  },
  {
    provider: "dashscope",
    api: "dashscope.native",
    modelPattern: "^qwen3\\.8",
    tools: "yes",
    schemaDialect: "union",
    arguments: "object",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://dashscope.aliyuncs.com/api/v1",
    baseURLIntl: "https://dashscope-intl.aliyuncs.com/api/v1",
    region: "cn",
    extraBody: { enable_thinking: false },
    notes:
      "Native MultiModalConversation.call with result_format message. Use this for qwen3.8-max rather than Generation.call.",
  },
  {
    provider: "dashscope",
    api: "dashscope.native",
    modelPattern: "^qwen",
    tools: "yes",
    schemaDialect: "union",
    arguments: "object",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://dashscope.aliyuncs.com/api/v1",
    baseURLIntl: "https://dashscope-intl.aliyuncs.com/api/v1",
    region: "cn",
    extraBody: { enable_thinking: false },
    notes: "Native DashScope Generation.call with result_format message.",
  },
  {
    provider: "moonshot",
    api: "chat.completions",
    modelPattern: "^kimi-",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://api.moonshot.cn/v1",
    baseURLIntl: "https://api.moonshot.ai/v1",
    region: "cn",
    notes: "Kimi OpenAI-compatible tools. K3 uses reasoning_effort.",
  },
  {
    provider: "zhipu",
    api: "chat.completions",
    modelPattern: "^glm-5v",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://open.bigmodel.cn/api/paas/v4",
    notes: "GLM multimodal. Streamed tool arguments arrive in chunks.",
  },
  {
    provider: "zhipu",
    api: "chat.completions",
    modelPattern: "^glm-",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://open.bigmodel.cn/api/paas/v4",
    notes: "GLM OpenAI-compatible tools. glm-5-turbo is the agent-oriented row.",
  },
  {
    provider: "qianfan",
    api: "chat.completions",
    modelPattern: "^ernie-",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    notes: "Baidu Qianfan ERNIE tools. Set baseURL to the Qianfan OpenAI-compat endpoint.",
  },
  {
    provider: "qianfan",
    api: "chat.completions",
    modelPattern: "^(kimi-k2|qwen3|deepseek-v3\\.1)",
    tools: "no",
    schemaDialect: "union",
    arguments: "string",
    parallel: false,
    strictDefault: false,
    auth: "bearer",
    notes:
      "Qianfan docs mark tools for this model as coming soon. Use an ERNIE model on Qianfan, or the model's native host.",
  },
  {
    provider: "ark",
    api: "chat.completions",
    modelPattern: "^ep-",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://ark.cn-beijing.volces.com/api/v3",
    baseURLIntl: "https://ark.ap-southeast.bytepluses.com/api/v3",
    region: "cn",
    modelIdKind: "endpoint",
    notes: "Doubao on Volcengine Ark. The model field is an endpoint id (ep-…), not a public slug.",
  },
  {
    provider: "ark",
    api: "chat.completions",
    modelPattern: ".",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://ark.cn-beijing.volces.com/api/v3",
    baseURLIntl: "https://ark.ap-southeast.bytepluses.com/api/v3",
    region: "cn",
    modelIdKind: "endpoint",
    notes:
      "Doubao Ark. Pass the endpoint id as model (ep-…). A public slug is not a valid model id on this host.",
  },
  {
    provider: "minimax",
    api: "chat.completions",
    modelPattern: "^MiniMax",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://api.minimax.cn/v1",
    baseURLIntl: "https://api.minimax.io/v1",
    region: "cn",
    extraBody: { thinking: { type: "disabled" } },
    notes:
      "Write back the full assistant tool-call message. Do not write back reasoning_content. Nested function_call is deprecated.",
  },
  {
    provider: "deepseek",
    api: "chat.completions",
    modelPattern: "^deepseek-chat",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://api.deepseek.com/v1",
    notes: "DeepSeek Chat Completions tools.",
  },
  {
    provider: "deepseek",
    api: "chat.completions",
    modelPattern: "^deepseek-reasoner",
    tools: "no",
    schemaDialect: "union",
    arguments: "string",
    parallel: false,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://api.deepseek.com/v1",
    notes: "deepseek-reasoner is not a tool-calling model. Use deepseek-chat.",
  },
  {
    provider: "stepfun",
    api: "chat.completions",
    modelPattern: "^step-3\\.(7|5)-flash",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://api.stepfun.com/v1",
    baseURLIntl: "https://api.stepfun.ai/v1",
    region: "cn",
    notes: "StepFun tools. Parameters root must be an object. At most 128 tools.",
  },
  {
    provider: "stepfun",
    api: "chat.completions",
    modelPattern: "^step-",
    tools: "no",
    schemaDialect: "union",
    arguments: "string",
    parallel: false,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://api.stepfun.com/v1",
    notes: "This StepFun model does not list tool calling. Use step-3.7-flash or step-3.5-flash.",
  },
  {
    provider: "yi",
    api: "chat.completions",
    modelPattern: "^yi-",
    tools: "unknown",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://api.lingyiwanwu.com/v1",
    notes:
      '01.AI Yi OpenAI-compat. Tool calling is not confirmed on the current public model card; pass api: "chat.completions" only after checking the live docs.',
  },
  {
    provider: "sensenova",
    api: "chat.completions",
    modelPattern: "^SenseNova",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    notes: "SenseTime SenseNova OpenAI-compatible chat. Set baseURL from the console.",
  },
  {
    provider: "hunyuan",
    api: "chat.completions",
    modelPattern: "^hunyuan-",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    notes:
      "Hunyuan via TokenHub or another OpenAI-compat gateway. Native Tencent Cloud uses hunyuan.tc3.",
  },
  {
    provider: "hunyuan",
    api: "hunyuan.tc3",
    modelPattern: "^hunyuan-(turbos|t1|functioncall)",
    tools: "yes",
    schemaDialect: "union",
    arguments: "object",
    parallel: true,
    strictDefault: false,
    auth: "tc3-hmac",
    notes:
      "Native Tencent Cloud ChatCompletions Tools. ToolChoice none/auto/custom. TC3-HMAC-SHA256 auth.",
  },
  {
    provider: "hunyuan",
    api: "hunyuan.tc3",
    modelPattern: "^hunyuan-",
    tools: "no",
    schemaDialect: "union",
    arguments: "object",
    parallel: false,
    strictDefault: false,
    auth: "tc3-hmac",
    notes: "Native Hunyuan tools only work on hunyuan-turbos, hunyuan-t1 and hunyuan-functioncall.",
  },
  {
    provider: "spark",
    api: "chat.completions",
    modelPattern: ".",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    notes: "iFlytek Spark HTTP OpenAI-style tools. Set baseURL from the console.",
  },
  {
    provider: "spark",
    api: "spark.hmac",
    modelPattern: ".",
    tools: "yes",
    schemaDialect: "union",
    arguments: "object",
    parallel: false,
    strictDefault: false,
    auth: "hmac",
    notes: "Classic Spark WebSocket HMAC (app_id, api_key, api_secret) with function_definition.",
  },
  {
    provider: "siliconflow",
    api: "chat.completions",
    modelPattern: ".",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://api.siliconflow.cn/v1",
    baseURLIntl: "https://api.siliconflow.com/v1",
    region: "cn",
    notes: "Gateway for Qwen, GLM, DeepSeek and others. Tool support follows the routed model.",
  },
];
