import type { Capability } from "../types.js";

export const LOCAL_CAPABILITIES: readonly Capability[] = [
  {
    provider: "ollama",
    api: "ollama.chat",
    modelPattern: "^(llama3\\.2|qwen3|mistral|firefunction)",
    tools: "yes",
    schemaDialect: "union",
    arguments: "object",
    parallel: true,
    strictDefault: false,
    auth: "none",
    baseURL: "http://127.0.0.1:11434",
    notes:
      "Native POST /api/chat. arguments is a JSON object; tool results use tool_name. See ollama.com/search?c=tool.",
  },
  {
    provider: "ollama",
    api: "chat.completions",
    modelPattern: "^(llama3\\.2|qwen3|mistral|firefunction)",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "none",
    baseURL: "http://127.0.0.1:11434/v1",
    notes: "Ollama OpenAI-compat /v1. Use the Chat Completions mapper, not the native one.",
  },
  {
    provider: "ollama",
    api: "ollama.chat",
    modelPattern: "^tinyllama",
    tools: "json-mode-only",
    schemaDialect: "union",
    arguments: "object",
    parallel: false,
    strictDefault: false,
    auth: "none",
    baseURL: "http://127.0.0.1:11434",
    notes: "tinyllama can emit JSON but has no tool calling.",
  },
  {
    provider: "ollama",
    api: "ollama.chat",
    modelPattern: ".",
    tools: "no",
    schemaDialect: "union",
    arguments: "object",
    parallel: false,
    strictDefault: false,
    auth: "none",
    baseURL: "http://127.0.0.1:11434",
    notes:
      "This Ollama tag is not listed for tool calling. Pick a model from ollama.com/search?c=tool.",
  },
  {
    provider: "vllm",
    api: "chat.completions",
    modelPattern: ".",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "none",
    baseURL: "http://127.0.0.1:8000/v1",
    notes: "vLLM OpenAI-compatible server. Tool support follows the loaded model.",
  },
  {
    provider: "llamacpp",
    api: "chat.completions",
    modelPattern: ".",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "none",
    baseURL: "http://127.0.0.1:8080/v1",
    notes: "llama.cpp server OpenAI-compat path.",
  },
  {
    provider: "lmstudio",
    api: "chat.completions",
    modelPattern: ".",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "none",
    baseURL: "http://127.0.0.1:1234/v1",
    notes: "LM Studio local server.",
  },
  {
    provider: "localai",
    api: "chat.completions",
    modelPattern: ".",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "none",
    baseURL: "http://127.0.0.1:8080/v1",
    notes: "LocalAI OpenAI-compat path.",
  },
  {
    provider: "litellm",
    api: "chat.completions",
    modelPattern: ".",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "http://127.0.0.1:4000/v1",
    notes: "LiteLLM proxy. Tool support follows the upstream model.",
  },
];
