import type { Capability } from "../types.js";

export const WESTERN_CAPABILITIES: readonly Capability[] = [
  {
    provider: "openai",
    api: "chat.completions",
    modelPattern: "^gpt-4o",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://api.openai.com/v1",
    notes: "Chat Completions tools. Nested function definitions.",
  },
  {
    provider: "openai",
    api: "chat.completions",
    modelPattern: "^gpt-4\\.1",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://api.openai.com/v1",
    notes: "Chat Completions tools.",
  },
  {
    provider: "openai",
    api: "responses",
    modelPattern: "^gpt-4o",
    tools: "yes",
    schemaDialect: "openai-strict",
    arguments: "string",
    parallel: true,
    strictDefault: true,
    auth: "bearer",
    baseURL: "https://api.openai.com/v1",
    notes:
      "Responses API function tools. Flat name/parameters; results are function_call_output items.",
  },
  {
    provider: "openai",
    api: "responses",
    modelPattern: "^gpt-5",
    tools: "yes",
    schemaDialect: "openai-strict",
    arguments: "string",
    parallel: true,
    strictDefault: true,
    auth: "bearer",
    baseURL: "https://api.openai.com/v1",
    notes: "GPT-5 family uses the Responses API for tool calling.",
  },
  {
    provider: "openai",
    api: "chat.completions",
    modelPattern: "^gpt-5\\.4",
    tools: "no",
    schemaDialect: "openai-strict",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://api.openai.com/v1",
    notes:
      "From GPT-5.4, Chat Completions rejects tool calling unless reasoning_effort is none. Use the Responses API.",
  },
  {
    provider: "openai",
    api: "responses",
    modelPattern: "^gpt-6",
    tools: "yes",
    schemaDialect: "openai-strict",
    arguments: "string",
    parallel: true,
    strictDefault: true,
    auth: "bearer",
    baseURL: "https://api.openai.com/v1",
    notes: "GPT-6 Astra requires the Responses API for tool calling.",
  },
  {
    provider: "openai",
    api: "chat.completions",
    modelPattern: "^gpt-6",
    tools: "no",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://api.openai.com/v1",
    notes: 'GPT-6 Astra requires the Responses API for tool calling. Pass api: "responses".',
  },
  {
    provider: "azure-openai",
    api: "chat.completions",
    modelPattern: ".",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "api-key",
    notes: "Azure/Foundry Chat Completions. Set baseURL to the deployment endpoint.",
  },
  {
    provider: "azure-openai",
    api: "responses",
    modelPattern: ".",
    tools: "yes",
    schemaDialect: "openai-strict",
    arguments: "string",
    parallel: true,
    strictDefault: true,
    auth: "api-key",
    notes: "Azure/Foundry Responses API. Use /openai/v1/ and function_call_output items.",
  },
  {
    provider: "anthropic",
    api: "anthropic.messages",
    modelPattern: "^claude-",
    tools: "yes",
    schemaDialect: "anthropic",
    arguments: "object",
    parallel: true,
    strictDefault: true,
    auth: "x-api-key",
    baseURL: "https://api.anthropic.com",
    notes: "Messages API tools use input_schema. Do not force tool_choice on newest models.",
  },
  {
    provider: "anthropic",
    api: "anthropic.toolRunner",
    modelPattern: "^claude-",
    tools: "yes",
    schemaDialect: "anthropic",
    arguments: "object",
    parallel: true,
    strictDefault: true,
    auth: "x-api-key",
    baseURL: "https://api.anthropic.com",
    notes: "Beta toolRunner / betaZodTool. Same plan schema as Messages.",
  },
  {
    provider: "google",
    api: "gemini.generateContent",
    modelPattern: "^gemini-",
    tools: "yes",
    schemaDialect: "gemini-openapi",
    arguments: "object",
    parallel: true,
    strictDefault: false,
    auth: "api-key",
    baseURL: "https://generativelanguage.googleapis.com/v1beta",
    notes:
      "generateContent functionDeclarations. Vertex uses the gemini-vertex dialect (uppercase types).",
  },
  {
    provider: "google",
    api: "gemini.interactions",
    modelPattern: "^gemini-",
    tools: "yes",
    schemaDialect: "gemini-openapi",
    arguments: "object",
    parallel: true,
    strictDefault: false,
    auth: "api-key",
    baseURL: "https://generativelanguage.googleapis.com/v1beta",
    notes:
      "Interactions API. tool_choice modes auto/any/none/validated. Do not force any by default.",
  },
  {
    provider: "bedrock",
    api: "bedrock.converse",
    modelPattern: "amazon.nova",
    tools: "yes",
    schemaDialect: "bedrock-nova",
    arguments: "object",
    parallel: true,
    strictDefault: true,
    auth: "aws-sigv4",
    notes:
      "Nova Converse tools only allow type, properties and required on objects. Use the loose plan schema.",
  },
  {
    provider: "bedrock",
    api: "bedrock.converse",
    modelPattern: ".",
    tools: "yes",
    schemaDialect: "union",
    arguments: "object",
    parallel: true,
    strictDefault: true,
    auth: "aws-sigv4",
    notes:
      "Bedrock Converse toolConfig.toolSpec. One wire format for Claude, Llama, Mistral and Command on Bedrock.",
  },
  {
    provider: "cohere",
    api: "cohere.chat",
    modelPattern: "^command",
    tools: "yes",
    schemaDialect: "union",
    arguments: "object",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://api.cohere.com/v2",
    notes:
      "Cohere Chat v2 tools. Results may include citation documents; Weftai returns text content.",
  },
  {
    provider: "groq",
    api: "chat.completions",
    modelPattern: ".",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://api.groq.com/openai/v1",
    notes: "OpenAI-compatible Chat Completions.",
  },
  {
    provider: "together",
    api: "chat.completions",
    modelPattern: ".",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://api.together.xyz/v1",
    notes: "OpenAI-compatible Chat Completions.",
  },
  {
    provider: "fireworks",
    api: "chat.completions",
    modelPattern: ".",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: false,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://api.fireworks.ai/inference/v1",
    notes: "OpenAI-compatible. Parallel tool calls are not reliable.",
  },
  {
    provider: "openrouter",
    api: "chat.completions",
    modelPattern: ".",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://openrouter.ai/api/v1",
    notes: "OpenAI-compatible gateway. Tool support follows the routed model.",
  },
  {
    provider: "openrouter",
    api: "responses",
    modelPattern: ".",
    tools: "yes",
    schemaDialect: "openai-strict",
    arguments: "string",
    parallel: true,
    strictDefault: true,
    auth: "bearer",
    baseURL: "https://openrouter.ai/api/v1",
    notes: "OpenRouter Responses-shaped endpoint.",
  },
  {
    provider: "xai",
    api: "chat.completions",
    modelPattern: "^grok-",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://api.x.ai/v1",
    notes: "xAI Grok Chat Completions tools.",
  },
  {
    provider: "xai",
    api: "responses",
    modelPattern: "^grok-",
    tools: "yes",
    schemaDialect: "openai-strict",
    arguments: "string",
    parallel: true,
    strictDefault: true,
    auth: "bearer",
    baseURL: "https://api.x.ai/v1",
    notes: "xAI also documents the Responses API for Grok.",
  },
  {
    provider: "mistral",
    api: "chat.completions",
    modelPattern: ".",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://api.mistral.ai/v1",
    notes: "Mistral Completions tools. Do not force tool_choice.",
  },
  {
    provider: "cerebras",
    api: "chat.completions",
    modelPattern: ".",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://api.cerebras.ai/v1",
    notes: "OpenAI-compatible Chat Completions.",
  },
  {
    provider: "nvidia-nim",
    api: "chat.completions",
    modelPattern: ".",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://integrate.api.nvidia.com/v1",
    notes: "NVIDIA NIM OpenAI-compatible tools.",
  },
  {
    provider: "cloudflare",
    api: "chat.completions",
    modelPattern: ".",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://api.cloudflare.com/client/v4/accounts",
    notes: "Workers AI / AI Gateway OpenAI-compatible path. Set the account-specific baseURL.",
  },
  {
    provider: "databricks",
    api: "chat.completions",
    modelPattern: ".",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    notes: "Databricks Foundation Model APIs. Set baseURL to the workspace serving endpoint.",
  },
  {
    provider: "perplexity",
    api: "chat.completions",
    modelPattern: "^sonar",
    tools: "no",
    schemaDialect: "union",
    arguments: "string",
    parallel: false,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://api.perplexity.ai",
    notes:
      "Sonar models are search-grounded and do not accept custom Weftai tools. Use a tool-capable model on this host.",
  },
  {
    provider: "deepinfra",
    api: "chat.completions",
    modelPattern: ".",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://api.deepinfra.com/v1/openai",
    notes: "OpenAI-compatible. Tool support follows the routed model.",
  },
  {
    provider: "sambanova",
    api: "chat.completions",
    modelPattern: ".",
    tools: "yes",
    schemaDialect: "union",
    arguments: "string",
    parallel: true,
    strictDefault: false,
    auth: "bearer",
    baseURL: "https://api.sambanova.ai/v1",
    notes: "OpenAI-compatible Chat Completions.",
  },
];
